// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wobplezgoznsippinqiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndvYnBsZXpnb3puc2lwcGlucWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMjUyMDUsImV4cCI6MjA2MjkwMTIwNX0.5f_bMH0gC3yuKRs3LWvh_5QFz4PveY3aUbLVEtoBnkM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);